site_url: https://www.quirkietimes.io/
logo_url: https://www.quirkietimes.io/icon.png

publish_mode: editorial_workflow
backend:
  name: git-gateway
  branch: master
  squash_merges: true

# used together with `npx netlify-cms-proxy-server`. https://www.netlifycms.org/docs/beta-features/#working-with-a-local-git-repository
local_backend: true

media_folder: static/img
public_folder: /img
# Docs: https://www.netlifycms.org/docs/configuration-options/#collections
collections:
  - label: 'Site settings'
    name: 'site'
    files:
      - label: 'Info'
        name: 'info'
        file: 'content/site/info.json'
        format: 'json'
        editor:
          preview: false
        fields:
          - { label: Site Name, name: sitename, widget: string, hint: 'This is used for the site title' }
          - {
              label: Site Description,
              name: sitedescription,
              widget: string,
              hint: 'This is used as descriptive text for links that link to this site',
            }
          - {
              label: Site Language,
              name: sitelang,
              widget: string,
              pattern: ['^[a-z]{2}([-])?([A-Za-z]{2})?$', 'Must match "xx" or "xx-XX" syntax (ex. "en" or "sv-SE")'],
            }
          # - { label: Site Email, name: siteemail, widget: string, required: false }
  - name: 'newsletters'
    label: 'Newsletters'
    folder: 'content/newsletters'
    create: true
    format: 'frontmatter'
    slug: '{{slug}}'
    editor:
       preview: true
    fields:
      - { label: 'Created Date', name: 'createdAt', widget: 'datetime', date_format: 'YYYY-MM-DD', time_format: false }
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Description', name: 'description', widget: 'string', required: false }
      - {
          label: 'Newsletter Issues',
          required: true,
          name: 'category',
          widget: 'select',
          default: 'issue-1',
          options:
            [
              { label: 'Issue 1', value: 'issue-1' },
              { label: 'Issue 2', value: 'issue-2' },
              { label: 'Issue 3', value: 'issue-3' },
              { label: 'Issue 4', value: 'issue-4' },
              { label: 'Issue 5', value: 'issue-5' },
              { label: 'Issue 6', value: 'issue-6' },
              { label: 'Issue 7', value: 'issue-7' },
              { label: 'Issue 8', value: 'issue-8' },
              { label: 'Issue 9', value: 'issue-9' },
              { label: 'Issue 10', value: 'issue-10' },
            ],
        }
      - {
          label: 'Content',
          name: 'content',
          widget: 'list',
          required: false,
          summary: '{{fields.item}}',
          field: { label: 'Item', name: 'item', widget: 'string' },
        }
      - { label: 'Body', name: 'body', widget: 'markdown', required: false }
  - name: 'articles'
    label: 'Articles'
    folder: 'content/articles'
    create: true
    format: 'frontmatter'
    slug: '{{slug}}'
    view_groups:
      - label: "Newsletter:"
        field: category
    editor:
       preview: true
    fields:
      - { label: 'Created Date', name: 'createdAt', widget: 'datetime', date_format: 'YYYY-MM-DD', time_format: false }
      - {
          label: 'Newsletter',
          required: true,
          name: 'category',
          widget: 'select',
          default: 'issue-1',
          options:
            [
              { label: 'Issue 1', value: 'issue-1' },
              { label: 'Issue 2', value: 'issue-2' },
              { label: 'Issue 3', value: 'issue-3' },
              { label: 'Issue 4', value: 'issue-4' },
              { label: 'Issue 5', value: 'issue-5' },
              { label: 'Issue 6', value: 'issue-6' },
              { label: 'Issue 7', value: 'issue-7' },
              { label: 'Issue 8', value: 'issue-8' },
              { label: 'Issue 9', value: 'issue-9' },
              { label: 'Issue 10', value: 'issue-10' },
              { label: 'Issue 11', value: 'issue-11' },
              { label: 'Issue 12', value: 'issue-12' },
              { label: 'Issue 13', value: 'issue-13' },
              { label: 'Issue 14', value: 'issue-14' },
              { label: 'Issue 15', value: 'issue-15' },
              { label: 'Issue 16', value: 'issue-16' },
              { label: 'Issue 17', value: 'issue-17' },
              { label: 'Issue 18', value: 'issue-18' },
              { label: 'Issue 19', value: 'issue-19' },
              { label: 'Issue 20', value: 'issue-20' },
            ],
        }
      - { label: 'Search Words', name: 'searchwords', widget: 'boolean', default: false, required: false }
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Description', name: 'description', widget: 'string', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown', required: false }
